### ISSUE TITLE
With the new Cloudfare configuration on FFnet FFF fails on the first try.

### ISSUE THREAD

**Issue by mcepl** [nsapa/fanfictionnet_ff_proxy#10]
```sh
stitny~/K/fanfiction$ fanficfare -u 'harmony/The Potter Timeline-ffnet_13844482.epub' 
Updating harmony/The Potter Timeline-ffnet_13844482.epub, URL: https://www.fanfiction.net/s/13844482/1/The-Potter-Timeline
.Traceback (most recent call last):
  File "/home/matej/.bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare', 'console_scripts', 'fanficfare')())
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 344, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 320, in dispatch
    do_download(url,
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 435, in do_download
    adapter.getStoryMetadataOnly()
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/adapters/base_adapter.py", line 313, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/adapters/adapter_fanfictionnet.py", line 130, in doExtractChapterUrlsAndMetadata
    canonicalurl = soup.select_one('link[rel=canonical]')['href']
TypeError: 'NoneType' object is not subscriptable
stitny~/K/fanfiction$ fanficfare -u 'harmony/The Potter Timeline-ffnet_13844482.epub'
Updating harmony/The Potter Timeline-ffnet_13844482.epub, URL: https://www.fanfiction.net/s/13844482/1/The-Potter-Timeline
.Do update - epub(52) vs url(53)
stitny~/K/fanfiction$ 
```
[fanfiction_proxy_log.txt](https://github.com/nsapa/fanfictionnet_ff_proxy/files/9465299/fanfiction_proxy_log.txt)

**Comment by mcepl** [comment]
THank you.

**Comment by mcepl** [comment]
I think this is actually still alive as before:

```
fun~/K/f/tmp$ fanficfare https://www.fanfiction.net/s/5012016
.Traceback (most recent call last):
  File "/home/matej/.bin/fanficfare", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/matej/.local/lib/python3.11/site-packages/fanficfare/cli.py", line 344, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/home/matej/.local/lib/python3.11/site-packages/fanficfare/cli.py", line 320, in dispatch
    do_download(url,
  File "/home/matej/.local/lib/python3.11/site-packages/fanficfare/cli.py", line 435, in do_download
    adapter.getStoryMetadataOnly()
  File "/home/matej/.local/lib/python3.11/site-packages/fanficfare/adapters/base_adapter.py", line 327, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/home/matej/.local/lib/python3.11/site-packages/fanficfare/adapters/adapter_fanfictionnet.py", line 129, in doExtractChapterUrlsAndMetadata
    canonicalurl = soup.select_one('link[rel=canonical]')['href']
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
fun~/K/f/tmp$ 
```
