### ISSUE TITLE
Dockerfile doesn't currently work

### ISSUE THREAD

**Issue by VictorVow** [nsapa/fanfictionnet_ff_proxy#19]
Using the latest repo, this is the terminal output for `make run`: 

```
docker build -t fanfiction_ff_proxy .
[+] Building 1.3s (22/22) FINISHED                                                                                                                   docker:default
 => [internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                0.0s
 => [internal] load build definition from Dockerfile                                                                                                           0.0s
 => => transferring dockerfile: 1.84kB                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/fedora:38                                                                                                   1.1s
 => [ 1/17] FROM docker.io/library/fedora:38@sha256:6fc00f83a1b6526b1c6562e30f552d109ba8e269259c6742a26efab1b7aef59e                                           0.0s
 => [internal] load build context                                                                                                                              0.0s
 => => transferring context: 199B                                                                                                                              0.0s
 => CACHED [ 2/17] RUN adduser -c "proxy user" proxy_user                                                                                                      0.0s
 => CACHED [ 3/17] RUN adduser -c "gui user" gui_user                                                                                                          0.0s
 => CACHED [ 4/17] RUN mkdir -p /opt/proxy/code /opt/proxy/workdir && chown proxy_user /opt/proxy/workdir                                                      0.0s
 => CACHED [ 5/17] WORKDIR /opt/proxy/workdir                                                                                                                  0.0s
 => CACHED [ 6/17] RUN dnf -y --refresh upgrade && dnf -y --setopt=install_weak_deps=False install xorg-x11-drivers x11vnc xdotool xorg-x11-xinit xorg-x11-xa  0.0s
 => CACHED [ 7/17] ADD requirements.txt .                                                                                                                      0.0s
 => CACHED [ 8/17] RUN su proxy_user -c "python3 -m pip install --user -U pip"                                                                                 0.0s
 => CACHED [ 9/17] RUN su proxy_user -c "python3 -m pip install --user -r requirements.txt"                                                                    0.0s
 => CACHED [10/17] RUN wget -O - -nv https://github.com/novnc/noVNC/archive/refs/tags/v1.4.0.tar.gz | tar -xz -C /opt/proxy/workdir/ && mv /opt/proxy/workdir  0.0s
 => CACHED [11/17] RUN wget -O - -nv https://github.com/novnc/websockify/archive/refs/tags/v0.11.0.tar.gz | tar -xz -C /opt/proxy/workdir/ && mv /opt/proxy/w  0.0s
 => CACHED [12/17] WORKDIR /tmp                                                                                                                                0.0s
 => CACHED [13/17] RUN rm -rf /opt/proxy/workdir && dnf -y clean all                                                                                           0.0s
 => CACHED [14/17] ADD docker_files/supervisord.conf /opt/proxy/code/supervisord.conf                                                                          0.0s
 => CACHED [15/17] ADD docker_files/xorg.conf /etc/X11/xorg.conf                                                                                               0.0s
 => CACHED [16/17] ADD chrome_content.py /opt/proxy/code/chrome_content.py                                                                                     0.0s
 => CACHED [17/17] RUN echo "allowed_users=anybody" > /etc/X11/Xwrapper.config                                                                                 0.0s
 => exporting to image                                                                                                                                         0.0s
 => => exporting layers                                                                                                                                        0.0s
 => => writing image sha256:d26b039e976693f9ab6ef35f075502df3a1f85280d05068e639ed18d836c8cec                                                                   0.0s
 => => naming to docker.io/library/fanfiction_ff_proxy                                                                                                         0.0s
docker run --rm -p 8888:8888 -p 8080:8080 fanfiction_ff_proxy
2023-10-05 13:09:14.829 UTC INFO main fanfictionnet_ff_proxy version 0.5.8 by Nicolas SAPA <nico@byme.at>
2023-10-05 13:09:14.829 UTC INFO main This Alpha software is licensed under CECILL-2.1
2023-10-05 13:09:14.831 UTC INFO main Running on Linux-6.2.0-34-generic-x86_64-with-glibc2.37
2023-10-05 13:09:17.160 UTC INFO undetected_chromedriver.patcher patching driver executable /home/proxy_user/.local/share/undetected_chromedriver/undetected_chromedriver
2023-10-05 13:09:17.190 UTC ERROR ProxiedBrowser(init) Failed to initialize Chrome: 'ChromeOptions' object has no attribute 'headless'
Traceback (most recent call last):
  File "/opt/proxy/code/chrome_content.py", line 826, in <module>
    driver = ProxiedBrowser(chrome_path, args.verbose, chrome_version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/proxy/code/chrome_content.py", line 229, in __init__
    raise e
  File "/opt/proxy/code/chrome_content.py", line 219, in __init__
    self.driver = driver = uc.Chrome(service_log_path=service_log_path,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proxy_user/.local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 398, in __init__
    if headless or options.headless:
                   ^^^^^^^^^^^^^^^^
AttributeError: 'ChromeOptions' object has no attribute 'headless'
make: *** [Makefile:5: run] Error 1
```
</details>

Kubuntu 23.04

**Comment by nsapa** [comment]
Yes, removed in 5778acb354df2e59bc59a3c7fa6be49147ee3761
It was a test and it never worked like I wanted.
