### ISSUE TITLE
nsapa_proxy: proxy 127.0.0.1:8888 unavailable

### ISSUE THREAD

**Issue by estherflails** [nsapa/fanfictionnet_ff_proxy#20]
Recently I usually can't seem to start it and get this or similar errors in command line:

```
2023-10-20 18:24:59.039 Közép-európai nyári ido  INFO main fanfictionnet_ff_proxy version 0.5.8 by Nicolas SAPA <nico@byme.at>
2023-10-20 18:24:59.040 Közép-európai nyári ido  INFO main This Alpha software is licensed under CECILL-2.1
2023-10-20 18:24:59.046 Közép-európai nyári ido  INFO main Running on Windows-10-10.0.19044-SP0
2023-10-20 18:25:01.045 Közép-európai nyári ido  INFO undetected_chromedriver.patcher patching driver executable C:\Users\User\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-10-20 18:25:01.439 Közép-európai nyári ido  ERROR ProxiedBrowser(init) Failed to initialize Chrome: 'ChromeOptions' object has no attribute 'headless'
Traceback (most recent call last):
  File "C:\Users\User\Documents\MEGAsync\files\fanfictionnet_ff_proxy-master\chrome_content.py", line 826, in <module>
    driver = ProxiedBrowser(chrome_path, args.verbose, chrome_version)
  File "C:\Users\User\Documents\MEGAsync\files\fanfictionnet_ff_proxy-master\chrome_content.py", line 229, in __init__
    raise e
  File "C:\Users\User\Documents\MEGAsync\files\fanfictionnet_ff_proxy-master\chrome_content.py", line 219, in __init__
    self.driver = driver = uc.Chrome(service_log_path=service_log_path,
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\__init__.py", line 398, in __init__
    if headless or options.headless:
AttributeError: 'ChromeOptions' object has no attribute 'headless'
```

But when it does mysteriously work and I tried to use it, this was the result in FFF's log: `nsapa_proxy: proxy 127.0.0.1:8888 unavailable`

Even though in command line it says:

```
2023-11-26 14:58:20.062 Közép-európai téli ido  INFO main fanfictionnet_ff_proxy version 0.5.8 by Nicolas SAPA <nico@byme.at>
2023-11-26 14:58:20.062 Közép-európai téli ido  INFO main This Alpha software is licensed under CECILL-2.1
2023-11-26 14:58:20.069 Közép-európai téli ido  INFO main Running on Windows-10-10.0.19044-SP0
2023-11-26 14:58:23.534 Közép-európai téli ido  INFO undetected_chromedriver.patcher patching driver executable C:\Users\User\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-11-26 14:58:24.238 Közép-európai téli ido  INFO ProxiedBrowser(init) chromedriver version 119.0.6045.105 (38c72552c5e15ba9b3117c0967a0fd105072d7c6-refs/branch-heads/6045@{#1103}) running as pid 9192 driving Chrome version 119.0.6045.160 running as pid 19340 with undetected_chromedriver 3.5.4
2023-11-26 14:58:24.282 Közép-európai téli ido  INFO ProxiedBrowser(init) Trying to load existing cookie...
2023-11-26 14:58:24.282 Közép-európai téli ido  INFO main Chrome is initialized & ready to works!
2023-11-26 14:58:24.283 Közép-európai téli ido  INFO main Listening on 127.0.0.1:8888
```

**Comment by estherflails** [comment]
Alright, so the issue was my dektop VPN. After turning it off it started working, but then I got stuck at the solve captcha part. It just kept reloading the page no matter how many times I clicked "Verify you are human". I tried opening Chrome, going to FF.net and solving it there and it worked fine, not sure why the page the program opened wouldn't work.

```
2024-01-27 19:24:16.180 Közép-európai téli ido  INFO main fanfictionnet_ff_proxy version 0.5.8 by Nicolas SAPA <nico@byme.at>
2024-01-27 19:24:16.181 Közép-európai téli ido  INFO main This Alpha software is licensed under CECILL-2.1
2024-01-27 19:24:16.189 Közép-európai téli ido  INFO main Running on Windows-10-10.0.19044-SP0
2024-01-27 19:24:17.341 Közép-európai téli ido  INFO undetected_chromedriver.patcher patching driver executable C:\Users\User\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2024-01-27 19:24:18.091 Közép-európai téli ido  INFO ProxiedBrowser(init) chromedriver version 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483}) running as pid 19004 driving Chrome version 120.0.6099.225 running as pid 26600 with undetected_chromedriver 3.5.4
2024-01-27 19:24:18.149 Közép-európai téli ido  INFO ProxiedBrowser(init) Trying to load existing cookie...
2024-01-27 19:24:18.149 Közép-európai téli ido  INFO main Chrome is initialized & ready to works!
2024-01-27 19:24:18.150 Közép-európai téli ido  INFO main Listening on 127.0.0.1:8888
2024-01-27 19:24:23.192 Közép-európai téli ido  INFO get_content Current URL = https://www.fanfiction.net/s/5230877/1/At-Gate-s-Edge, page title = Just a moment..., mimetype = text/html
2024-01-27 19:24:23.201 Közép-európai téli ido  INFO cloudfare_clickcaptcha Waiting for user to resolve the captcha: press Enter to continue
```
